### PR TITLE
pbdADIOS merge request

### PR DESCRIPTION
**Pull request by YupingLu**
Hi Drew,

Please review. Thanks!

### CODE REVIEW

**Comment by wrathematics** [comment]
# R problems

* Do not use `<<-` for assignment. If you have global values you need to keep track of, you need to create a custom environment and store/look up things there with `assign()` and `get()`. You can see examples of this in the remoter package.
* Do not list pbdMPI under both Depends and Imports in the DESCRIPTION.
* the `demo/` tree is not correctly structured.  First, your data should go in `inst/`. You also need a `00Index` file.
* None (or at least most) of your help files are mal-formed. Each one needs a description.
* You have numerous functions which are exported but not documented. You need to either not export them or to document them. If you expect a user to ever call them, then they should be exported. If a user will never call them, do not export them.


# C problems

* There are several very serious warnings that should be fixed. If you're using a Mac or Linux, you should add the line `CFLAGS=-O2 -Wall -pedantic` to your `~/.R/Makevars` file to make sure you see them all.
* You can not call `exit` or `puts`. You have to manage printing and error handling the R way.

# Misc

* It does not build with ADIOS 1.7.0. I had to grab the latest, 1.10.0.  Please note the version dependency in the readme.
* It's perhaps too late to fix this, but in the future, don't change formatting for a project you don't own (indents, bracing, etc.). This is very anti-social.


Please make the necessary corrections.  You should run:

```
R --vanilla CMD check pbdADIOS_0.1-0.tar.gz --install-args="--configure-args=--with-adios-home=$HOME/libs/adios-1.10.0/install"
```

To make sure there are no WARNINGs and no NOTEs.

**Comment by wrathematics** [comment]
Feel free to ask me any questions you may have. Once you fix something and push to github, that push will appear here and I will review it.

**Comment by YupingLu** [comment]
Got it. Thanks Drew. I'll fix the problems listed above.

**Comment by YupingLu** [comment]
Hi , Drew. How do you get the package tarball using 'R CMD build'? I don't know how to pass the value of --with-adios-home to R while building it. Currently I use tar command to get the tarball.

>* checking DESCRIPTION meta-information ... NOTE
Checking should be performed on sources prepared by ‘R CMD build’.

>* checking package vignettes in ‘inst/doc’ ... WARNING
Package vignette without corresponding PDF/HTML:
   ‘pbdADIOS.Rmd’

**Comment by wrathematics** [comment]
Just wanted to say that I'm still looking at this, but other deadlines are making it difficult to devote a lot of time to it.

If those are the only two NOTE/WARNING's generated, then the package is probably in pretty good shape.  Still you should always check on an `R CMD build` generated tarball.  To do this for a package with system dependencies, you can add the `--no-build-vignettes` option.  The only thing `R CMD build` needs the installed package for is vignette building, so adding that flag should do the trick.

**Comment by wrathematics** [comment]
PS, you need to add yourself to the list in `Authors@R` of the `DESCRIPTION` file.  If you publish (or plan to) under "Yuping Lu", then the line is `person("Yuping", "Lu", role="aut")`.  Watch out for the trailing commas.

For now, just put your name anywhere.  I'll let @go-ski set the final author order (it needs to be rearranged).

**Comment by YupingLu** [comment]
One WARNING left. I guess it's related to the `--no-build-vignettes` option. Take your time. If you find new problems, just let me know.

> * checking package vignettes in ‘inst/doc’ ... WARNING 
Package vignette without corresponding PDF/HTML:
   ‘pbdADIOS.Rmd’

**Pull request merged**
